{
 "title": "Evidently AI data",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Column Drift for Jan to Apr 2024",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", num_drifted_columns FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Median Experience for Jan to Feb 24 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", median_experience FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction drift for  Jan to Apr 2024",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", prediction_drift FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Salary prediction rmse for Jan to Apr 2024",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", rmse FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}